spring.application.name=chatCriptografado

# Conexao com a porta 5433 e desativando SSL
spring.datasource.url=jdbc:postgresql://localhost:5432/chatCriptografado?sslmode=disable
spring.datasource.driverClassName=org.postgresql.Driver

spring.datasource.username=postgres
spring.datasource.password=password

# Configuracoes do Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

# Timeout do Hikari
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.maximum-pool-size=5